kind: Secret
apiVersion: v1
metadata:
  name: test-secret
  annotations:
    avp.kubernetes.io/path: projects/137142661179/secrets/test
    avp.kubernetes.io/secret-version: "1"
type: Opaque
data:
  password: <test>  
