kind: Secret
apiVersion: v1
metadata:
  name: test-secret
  annotations:
    avp.kubernetes.io/path: projects/251360461095/secrets/subingestion_pg_dev_pass
    avp.kubernetes.io/secret-version: "latest"
type: Opaque
data:
  password: <subingestion_pg_dev_pass>  
